// Generates seed/bottles.json (starter bottles from fictional castaways) and injects the same array
// into index.html's OFFLINE_SEEDS marker so the offline harbour has practice bottles.
const fs = require('fs'); const path = require('path');
const P = (name, age, interests, temper, pace, mood, tz, lang='en') => ({ name, age, interests, temper, pace, mood, tz, lang });
const daysAgo = d => new Date(Date.now() - d*86400000).toISOString();
const B = [
 ['romance', P('Ines',2,['sea','poetry','coffee','late nights'],2,4,'lonely',1,'pt'), 'I don\'t know who will find this. I only know I wanted to write to someone who isn\'t already tired of me. Tell me one thing you love that nobody asks you about. I\'ll tell you mine: the sound of the harbour chain at 3am, when the boats pull against it like they want to leave too.'],
 ['romance', P('Tomasz',3,['hiking','cooking','history','animals'],3,3,'hopeful',1,'pl'), 'My grandmother met my grandfather because of a letter delivered to the wrong flat. I\'m not asking the sea for the same luck. I\'m just saying I\'ve stopped ruling it out. What was the last small thing that made you happy?'],
 ['romance', P('Maya',1,['music','film','cities','late nights'],4,2,'playful',-5), 'Rules for whoever fishes this up: 1) You have to tell me your favourite song right now, not your all-time one. 2) No talking about work. 3) If we get to ten letters we have to invent a secret handshake we\'ll never use. Deal?'],
 ['lessons', P('Ruth',4,['gardens','books','animals','history'],2,5,'calm',0), 'I am sixty-one and I have learned exactly one thing worth writing down: nobody is thinking about you as much as you think they are. It sounds cruel, but it is the most freeing sentence I know. Wear the coat. Sing on the bus. Send the letter.'],
 ['lessons', P('Dev',2,['coding','science','games','coffee'],3,3,'thoughtful',5.5), 'I spent three years building something nobody used. What I\'d tell my past self isn\'t "don\'t"; it\'s "show someone after three weeks, not three years." Does anyone else have a lesson that cost too much to learn?'],
 ['lessons', P('Halima',3,['cooking','travel','philosophy','music'],3,4,'hopeful',3,'ar'), 'When my father was dying he said the days he regretted were not the ones where he failed, but the ones where he didn\'t try because he was afraid of looking foolish. I think about it whenever I hesitate before speaking to a stranger. Hello, stranger.'],
 ['confess', P('Anonymous',0,['late nights','film','cities'],2,3,'restless',-8), 'I still have my ex\'s Netflix password. Not because I use it. Because logging out would make it real. That\'s the whole confession. It feels smaller now that it\'s in a bottle.'],
 ['confess', P('J.',2,['music','art','coffee','poetry'],2,4,'lonely',2,'de'), 'I told everyone I moved here for the job. I moved here because I wanted to be somewhere nobody knew the old version of me. It worked, mostly. The problem is that nobody knows the new one either.'],
 ['confess', P('Marisol',3,['cooking','animals','gardens','football'],4,2,'playful',-6,'es'), 'I pretend my dog\'s vet appointments run long so I can sit in the car for twenty minutes with the radio on. That\'s it. Twenty minutes where nobody needs anything. Do you have a place like that?'],
 ['question', P('Kenji',2,['science','philosophy','games','hiking'],2,3,'thoughtful',9,'ja'), 'If you could know the exact number of times you\'ll see the ocean for the rest of your life, would you want to? I keep changing my answer. I\'m curious what yours is tonight.'],
 ['question', P('Priya',1,['books','film','art','cities'],3,3,'hopeful',5.5), 'What is something you were completely wrong about, and glad to be? Mine: I thought I hated cities. Turns out I hated the one I grew up in.'],
 ['question', P('Owen',3,['football','history','cooking','travel'],5,2,'playful',0), 'Serious question for a stranger: what\'s the best sandwich you have ever eaten, and where were you when you ate it? The where matters more than the sandwich. I\'ll go second.'],
 ['story', P('Agnes',4,['sea','history','books','gardens'],2,5,'calm',-1,'fr'), 'In 1994 my brother threw a bottle off the ferry at Roscoff. In 2011 a woman in Cornwall wrote to say she\'d found it on a beach the morning after her divorce was final, and that "it made a bad day strange instead of just bad." That\'s all I want this one to do.'],
 ['story', P('Bakary',2,['music','coding','cities','late nights'],3,4,'restless',0), 'Last winter the power went out on our whole street and everyone came outside like it was a fire drill. A neighbour I had never spoken to in four years brought out a guitar. Now we have a group chat. It took a blackout. What did it take on your street?'],
 ['story', P('Linnea',3,['hiking','animals','sea','science'],2,4,'thoughtful',1,'sv'), 'I once got lost on a fell walk and was found by a sheepdog who simply refused to leave me alone until I followed it to a farmhouse. The farmer said she does that. She just picks people. I think about being picked a lot.'],
 ['cheer', P('Sam',2,['games','music','coffee','film'],4,2,'hopeful',-5), 'Whoever you are: you got up today. You\'re out here fishing for messages instead of doomscrolling. That\'s two wins before lunch. Tell me a third and I\'ll believe you.'],
 ['cheer', P('Nadia',3,['gardens','cooking','books','animals'],3,3,'calm',2,'ru'), 'I planted tomatoes in April knowing my landlord might sell the flat by summer. He did. But somebody is eating those tomatoes. Plant the thing anyway. I mean it in whatever way you need me to mean it.'],
 ['cheer', P('Theo',1,['football','hiking','science','travel'],5,2,'playful',10), 'Greetings from the far side of the clock. It is already tomorrow here and I can confirm: it\'s fine. You get there. Whatever tonight is, it\'s already behind someone.'],
 ['joke', P('Fran',3,['film','coffee','cities','art'],4,2,'playful',-3), 'I told my therapist I keep hearing the sea. She said that\'s normal, I live by the sea. I said no, it\'s in my headphones, I can\'t work out how to change the app. Anyway she charged me for the full hour. Got a better one?'],
 ['joke', P('Mikael',2,['coding','games','science','late nights'],2,3,'restless',2,'fi'), 'Threw a bottle in last week with a joke about recursion. Still waiting for it to come back. Meanwhile: why did the crab never share? Because it was shellfish. Yes, I know. Reply with a worse one and I\'ll respect you.'],
 ['romance', P('Cleo',2,['art','poetry','sea','travel'],3,5,'thoughtful',-7), 'I\'m not looking for love, I\'m looking for the kind of letter you read twice. If you\'re the kind of person who reads things twice, write back. Tell me the last line of the book on your nightstand.'],
 ['question', P('Ibrahim',3,['philosophy','history','coffee','cooking'],2,5,'calm',3,'tr'), 'Do you think people are mostly the same everywhere, or mostly different? I have moved countries three times and I change my mind every time the coffee is good.'],
 ['story', P('Wren',1,['animals','gardens','music','poetry'],2,3,'lonely',-8), 'My first week alone in a new city, a crow started leaving bottle caps on my windowsill. I\'ve started leaving peanuts. We are, I think, friends now. It is the only friend I have here. It\'s a good one though.'],
 ['lessons', P('Gus',4,['sea','football','cooking','history'],4,3,'hopeful',10), 'Forty years on trawlers. The lesson: the sea doesn\'t care, and that\'s the good news. It means you don\'t have to take any of it personally. Apply to weather, bosses, and most of the internet.'],
];
const bottles = B.map(([category, profile, text], i) => ({
  id: 'b_seed' + String(i+1).padStart(2,'0'), authorId: 'castaway_' + profile.name.toLowerCase().replace(/[^a-z]/g,'') + i,
  authorName: profile.name, profile, category, text, createdAt: daysAgo(1 + (i*7)%40), status: 'floating', hops: (i*3)%4===0?1:0, seed: true,
}));
fs.writeFileSync(path.join(__dirname,'bottles.json'), JSON.stringify(bottles, null, 1));
const html = path.join(__dirname,'..','index.html'); let s = fs.readFileSync(html,'utf8');
s = s.replace(/\/\*SEEDS\*\/[\s\S]*?\/\*\/SEEDS\*\//, '/*SEEDS*/' + JSON.stringify(bottles) + '/*/SEEDS*/');
fs.writeFileSync(html, s);
console.log(bottles.length, 'seed bottles written');
